import { Platform, Image } from 'react-native';
import * as ImageManipulator from 'expo-image-manipulator';
import { fetchWithTimeout } from './fetchWithTimeout';

/**
 * Driver onboarding / profile service — backend-only (live MacrushBackend).
 *
 * This app DOES NOT talk to Firestore or Firebase Storage anymore:
 *   - All documents (driver reports) are stored in MongoDB by the backend.
 *   - All file uploads are stored in AWS S3 by the backend.
 *   - Firebase is used for authentication only (idToken passed as Bearer).
 *
 * Endpoints used (see backend routes/):
 *   GET  /api/firestore/drivers/:id          -> driver profile (MongoDB)
 *   POST /api/firestore/drivers              -> create driver (onboarding)
 *   PUT  /api/firestore/drivers/:id          -> update driver
 *   GET  /api/drivers/by-phone/:phone        -> lookup driver by phone
 *   GET  /api/drivers/:uid/availability-state
 *   PATCH /api/drivers/:uid/availability-state
 *   POST /api/drivers/:uid/availability-logs
 *   POST /api/uploads/profile-photo          -> S3
 *   POST /api/uploads/driver-onboarding-assets -> S3
 *   POST /api/uploads/driver-report          -> S3
 */

export interface OnboardingData {
  // Personal Info
  phoneNumber: string;
  fullName: string;

  // Documents
  photoUri: string;
  drivingLicenseUri: string;
  identityProofUri: string;

  // Vehicle Details
  vehicleNumber: string;
  vehicleType: string;
  vehicleCapacity: string;
  bodyType: string;
  rcBookUri: string;
  insuranceUri: string;
  vehiclePhotoUris: string[];

  // First-page previews for non-image documents (e.g. PDFs), generated by the
  // backend into S3. Preferred over the raw Uri when rendering thumbnails.
  drivingLicensePreviewUri?: string;
  identityProofPreviewUri?: string;
  rcBookPreviewUri?: string;
  insurancePreviewUri?: string;

  // Bank Details
  bankName: string;
  accountNumber: string;
  ifscCode: string;
  upiId?: string;

  // Verification Status
  verificationStatus: 'pending' | 'verified' | 'rejected' | 'suspended';
  documentVerificationStatus?: string;
  verified?: boolean;
  status?: string;
  verifiedDate?: string;
  verifiedAt?: string;
  rejectionMessage?: string;
  rejectionReason?: string;
  rejectedDocuments?: string[];
  verificationNotes?: string;
  profilePhotoUrl?: string;
  activeStatus?: boolean;

  // Metadata
  createdAt?: string;
  updatedAt?: string;
  submittedAt?: string;
}

export interface DriverReportData {
  category: string;
  issueType: string;
  description: string;
  imageUris: string[];
}

type VerificationStatus = 'pending' | 'verified' | 'rejected' | 'suspended';
export type DriverAvailabilityStatus = 'online' | 'offline';
export type DriverAvailabilityState = {
  status: DriverAvailabilityStatus;
  changedAt?: string | Date | null;
};

const getApiBaseUrl = () =>
  (process.env.EXPO_PUBLIC_API_BASE_URL || 'http://localhost:5000').replace(/\/$/, '');

const getApiErrorMessage = (responseBody: unknown, fallback: string) => {
  if (responseBody && typeof responseBody === 'object' && 'error' in responseBody) {
    const error = (responseBody as { error?: unknown }).error;
    if (typeof error === 'string') return error;
    if (error && typeof error === 'object' && 'message' in error) {
      const message = (error as { message?: unknown }).message;
      if (typeof message === 'string') return message;
    }
  }
  return fallback;
};

const isRemoteUrl = (uri: string) => /^https?:\/\//i.test(uri);

const isPhoneIdentifier = (value: string) =>
  value.startsWith('+') || /^\d{10,15}$/.test(value);

const blobToDataUrl = (blob: Blob) =>
  new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === 'string') resolve(reader.result);
      else reject(new Error('Failed to read selected file'));
    };
    reader.onerror = () => reject(new Error('Failed to read selected file'));
    reader.readAsDataURL(blob);
  });

const localUriToDataUrl = async (uri: string) => {
  if (uri.startsWith('data:')) return uri;
  const response = await fetchWithTimeout(uri);
  const blob = await response.blob();
  return blobToDataUrl(blob);
};

// ----------------------------------------------------------------------------
// Native on-device image compression (Android / iOS).
//
// The backend enforces `express.json({ limit: '16mb' })`, and a single
// full-resolution camera photo base64-encoded can exceed that cap on its own
// (previously this surfaced as `request entity too large`, HTTP 413). We
// downscale + re-encode to JPEG here so every asset stays small before upload.
// ----------------------------------------------------------------------------
const NATIVE_IMAGE_MAX_DIM = 1600; // longest edge in px
const NATIVE_IMAGE_QUALITY = 0.7;

const getImageDimensions = (uri: string) =>
  new Promise<{ width: number; height: number }>((resolve, reject) => {
    Image.getSize(
      uri,
      (width, height) => resolve({ width, height }),
      (error) => reject(error)
    );
  });

const nativeImageToDataUrl = async (uri: string): Promise<string | null> => {
  try {
    const size = await getImageDimensions(uri).catch(() => null);

    const actions: ImageManipulator.Action[] = [];
    if (size && Math.max(size.width, size.height) > NATIVE_IMAGE_MAX_DIM) {
      // Downscale only the longest edge; expo keeps aspect ratio.
      const isPortrait = size.height > size.width;
      actions.push({
        resize: {
          [isPortrait ? 'height' : 'width']: NATIVE_IMAGE_MAX_DIM,
        } as any,
      });
    }

    const result = await ImageManipulator.manipulateAsync(uri, actions, {
      compress: NATIVE_IMAGE_QUALITY,
      format: ImageManipulator.SaveFormat.JPEG,
      base64: true,
    });

    if (result.base64) return `data:image/jpeg;base64,${result.base64}`;
    return localUriToDataUrl(result.uri || uri);
  } catch (error) {
    // Non-image files (e.g. PDF RCs) can't be processed — fall back to raw read.
    console.warn('Native image compression failed, falling back to raw upload:', error);
    return localUriToDataUrl(uri);
  }
};

const resizeWebImageToDataUrl = async (
  imageUri: string,
  size = 256,
  quality = 0.82
): Promise<string> => {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    throw new Error('Web image resizing is only available in a browser');
  }

  const image = new window.Image();
  await new Promise<void>((resolve, reject) => {
    image.onload = () => resolve();
    image.onerror = () => reject(new Error('Failed to load selected image'));
    image.src = imageUri;
  });

  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;

  const context = canvas.getContext('2d');
  if (!context) throw new Error('Unable to prepare selected image');

  const sourceSize = Math.min(image.width, image.height);
  const sourceX = (image.width - sourceSize) / 2;
  const sourceY = (image.height - sourceSize) / 2;

  context.drawImage(image, sourceX, sourceY, sourceSize, sourceSize, 0, 0, size, size);
  return canvas.toDataURL('image/jpeg', quality);
};

// ============================================================================
// AWS S3 uploads (via the live backend)
// ============================================================================

const resolveUploadDataUrl = async (uri: string, maxWebSize = 1024, webQuality = 0.8) => {
  if (!uri) return null;
  if (uri.startsWith('data:')) return uri;
  if (Platform.OS === 'web') return resizeWebImageToDataUrl(uri, maxWebSize, webQuality);
  // Native: compress/resize on-device so the request stays well under the
  // backend's JSON body limit (fixes `request entity too large` on Android).
  return nativeImageToDataUrl(uri);
};

type OnboardingUploadAsset = {
  type: string;
  uri: string;
  index?: number;
};

/**
 * Per-request ceiling for a single image asset.
 *
 * The backend enforces `express.json({ limit: '16mb' })` (see MachrushBackend/app.js),
 * and it throws `request entity too large` (HTTP 413) when a request body exceeds it.
 * We therefore upload ONE asset per request and keep each well under the cap instead
 * of sending all base64-encoded images together in a single huge body.
 */
const MAX_SINGLE_UPLOAD_BYTES = 10 * 1024 * 1024; // ~10 MB < 16 MB server cap

const uploadOnboardingAssetsViaBackend = async (
  uid: string,
  assets: OnboardingUploadAsset[],
  idToken: string
): Promise<{
  type: string;
  index?: number;
  url: string;
  previewCanonicalUrl?: string;
  previewUrl?: string;
}[]> => {
  const uploaded: {
    type: string;
    index?: number;
    url: string;
    previewCanonicalUrl?: string;
    previewUrl?: string;
  }[] = [];

  for (const asset of assets) {
    if (!asset.uri || isRemoteUrl(asset.uri)) continue; // already hosted / remote, skip

    const dataUrl = await resolveUploadDataUrl(asset.uri);
    if (!dataUrl) continue;

    if (dataUrl.length > MAX_SINGLE_UPLOAD_BYTES) {
      throw new Error(
        `The file for "${asset.type}" is too large to upload (${(
          dataUrl.length /
          1024 /
          1024
        ).toFixed(1)} MB). Please retake or choose a smaller image/document and try again.`
      );
    }

    // Send this single asset in its OWN request so the body never grows past the cap.
    const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/uploads/driver-onboarding-assets`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${idToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ uid, assets: [{ type: asset.type, index: asset.index, dataUrl }] }),
    });

    const responseBody = await response.json().catch(() => null);
    if (!response.ok || !responseBody?.success) {
      throw new Error(getApiErrorMessage(responseBody, 'Failed to upload onboarding file'));
    }

    const uploadedAsset = (responseBody.assets || [])[0];
    if (uploadedAsset?.url) uploaded.push(uploadedAsset);
  }

  return uploaded;
};

/**
 * Diagnostics helper — logs the approximate size of every onboarding field before
 * the Firestore/MongoDB write. This lets you find which field is unexpectedly huge
 * (e.g. an image stored as a Base64 `data:` string instead of a storage URL).
 */
export const logOnboardingFieldSizes = (
  data: Record<string, any>,
  label = 'onboarding'
): void => {
  const byteSize = (value: unknown): number => {
    if (typeof value === 'string') return value.length; // Base64/utf8 bytes (approx)
    if (Array.isArray(value)) return value.reduce((sum, item) => sum + byteSize(item), 0);
    if (value && typeof value === 'object') return JSON.stringify(value).length;
    return 0;
  };

  const total = byteSize(data);
  console.log(
    `📦 ${label} payload total: ${(total / 1024 / 1024).toFixed(2)} MB (${total.toLocaleString()} bytes)`
  );
  for (const key of Object.keys(data)) {
    const size = byteSize(data[key]);
    if (size > 512 * 1024) {
      console.warn(`   • ${key}: ${(size / 1024 / 1024).toFixed(2)} MB (LARGE — should be a URL)`);
    }
  }
};

const uploadProfilePhotoViaBackend = async (
  uid: string,
  imageData: string,
  idToken: string
) => {
  const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/uploads/profile-photo`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${idToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ uid, imageData }),
  });

  const responseBody = await response.json().catch(() => null);
  if (!response.ok || !responseBody?.success) {
    throw new Error(getApiErrorMessage(responseBody, 'Failed to upload profile photo'));
  }

  return responseBody.imageUrl as string;
};

const submitDriverReportViaBackend = async (
  uid: string,
  reportInput: DriverReportData,
  idToken: string
) => {
  const imageDataUrls = (
    await Promise.all(
      (reportInput.imageUris || []).map((uri) => resolveUploadDataUrl(uri, 720, 0.76))
    )
  ).filter(Boolean) as string[];

  const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/uploads/driver-report`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${idToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      uid,
      category: reportInput.category,
      issueType: reportInput.issueType,
      description: reportInput.description,
      imageDataUrls,
    }),
  });

  const responseBody = await response.json().catch(() => null);
  if (!response.ok || !responseBody?.success) {
    throw new Error(getApiErrorMessage(responseBody, 'Failed to submit report'));
  }

  return responseBody.reportId as string;
};

// ============================================================================
// MongoDB writes (via the live backend)
// ============================================================================

const storeDriverViaBackend = async (
  uid: string,
  data: Record<string, any>,
  idToken?: string | null
) => {
  const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/firestore/drivers`, {
    method: 'POST',
    headers: {
      ...(idToken ? { Authorization: `Bearer ${idToken}` } : {}),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ uid, ...data }),
  });

  const responseBody = await response.json().catch(() => null);
  if (!response.ok || !responseBody?.success) {
    throw new Error(getApiErrorMessage(responseBody, 'Failed to store onboarding data'));
  }
  return responseBody.data;
};

const updateDriverViaBackend = async (
  uid: string,
  patch: Record<string, unknown>,
  idToken?: string | null
) => {
  const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/firestore/drivers/${encodeURIComponent(uid)}`, {
    method: 'PUT',
    headers: {
      ...(idToken ? { Authorization: `Bearer ${idToken}` } : {}),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(patch),
  });

  const responseBody = await response.json().catch(() => null);
  if (!response.ok || !responseBody?.success) {
    throw new Error(getApiErrorMessage(responseBody, 'Failed to update driver'));
  }
  return responseBody.data;
};

// ============================================================================
// Driver availability (via the live backend)
// ============================================================================

const setDriverAvailabilityStateViaBackend = async (
  uid: string,
  status: DriverAvailabilityStatus,
  changedAt: string,
  idToken: string
) => {
  const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/drivers/${encodeURIComponent(uid)}/availability-state`, {
    method: 'PATCH',
    headers: {
      Authorization: `Bearer ${idToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ status, changedAt }),
  });

  const responseBody = await response.json().catch(() => null);
  if (!response.ok || !responseBody?.success) {
    throw new Error(getApiErrorMessage(responseBody, 'Failed to update driver availability'));
  }
};

const createDriverAvailabilityLogViaBackend = async (
  uid: string,
  status: DriverAvailabilityStatus,
  changedAt: string,
  idToken: string
) => {
  const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/drivers/${encodeURIComponent(uid)}/availability-logs`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${idToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ status, changedAt }),
  });

  const responseBody = await response.json().catch(() => null);
  if (!response.ok || !responseBody?.success) {
    throw new Error(getApiErrorMessage(responseBody, 'Failed to create driver availability log'));
  }
};

const getDriverAvailabilityStateViaBackend = async (
  uid: string,
  idToken: string
): Promise<DriverAvailabilityState | null> => {
  const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/drivers/${encodeURIComponent(uid)}/availability-state`, {
    headers: {
      Authorization: `Bearer ${idToken}`,
    },
  });

  const responseBody = await response.json().catch(() => null);
  if (!response.ok || !responseBody?.success || !responseBody?.data) return null;

  const state = responseBody.data;
  if (state?.status === 'online' || state?.status === 'offline') {
    return { status: state.status, changedAt: state.changedAt || null };
  }
  return null;
};

// ============================================================================
// Verification status resolution
// ============================================================================

const normalizeVerificationStatus = (status: unknown): VerificationStatus | null => {
  if (typeof status !== 'string') return null;
  const normalized = status.trim().toLowerCase();

  if (normalized === 'verified' || normalized === 'approved') return 'verified';
  if (
    normalized === 'pending' ||
    normalized === 'waiting' ||
    normalized === 'waiting for verification' ||
    normalized === 'waiting for approval'
  ) {
    return 'pending';
  }
  if (normalized === 'rejected') return 'rejected';
  if (
    normalized === 'suspend' ||
    normalized === 'suspended' ||
    normalized === 'blocked' ||
    normalized === 'block'
  ) {
    return 'suspended';
  }
  return null;
};

/**
 * Resolve a driver's verification status from a raw driver document.
 * Mirrors the backend admin logic across the multiple fields it writes.
 * Suspension always wins.
 */
export const resolveDriverVerificationStatus = (
  data: Record<string, any> | null | undefined
): VerificationStatus | null => {
  if (!data) return null;

  const vStatus = normalizeVerificationStatus(data.verificationStatus);
  const dStatus = normalizeVerificationStatus(data.documentVerificationStatus);
  const statusField = normalizeVerificationStatus(data.status);

  if (
    vStatus === 'suspended' ||
    dStatus === 'suspended' ||
    statusField === 'suspended'
  ) {
    return 'suspended';
  }

  if (
    vStatus === 'verified' ||
    dStatus === 'verified' ||
    statusField === 'verified' ||
    data.verified === true
  ) {
    return 'verified';
  }

  if (
    vStatus === 'rejected' ||
    dStatus === 'rejected' ||
    statusField === 'rejected'
  ) {
    return 'rejected';
  }

  if (
    vStatus === 'pending' ||
    dStatus === 'pending' ||
    statusField === 'pending'
  ) {
    return 'pending';
  }

  if (data.submittedAt || data.createdAt) return 'pending';
  return null;
};

// ============================================================================
// Onboarding uploads (assets -> S3 via backend)
// ============================================================================

const uploadOnboardingAssets = async (
  uid: string,
  onboardingData: Omit<OnboardingData, 'createdAt' | 'updatedAt' | 'submittedAt'>,
  idToken?: string
): Promise<Omit<OnboardingData, 'createdAt' | 'updatedAt' | 'submittedAt'>> => {
  const vehiclePhotoUris = onboardingData.vehiclePhotoUris || [];

  const assets: OnboardingUploadAsset[] = [
    { type: 'photoUri', uri: onboardingData.photoUri },
    { type: 'drivingLicenseUri', uri: onboardingData.drivingLicenseUri },
    { type: 'identityProofUri', uri: onboardingData.identityProofUri },
    { type: 'rcBookUri', uri: onboardingData.rcBookUri },
    { type: 'insuranceUri', uri: onboardingData.insuranceUri },
    ...vehiclePhotoUris.map((uri, index) => ({ type: 'vehiclePhotoUris', uri, index })),
  ].filter((asset) => asset.uri && !isRemoteUrl(asset.uri));

  if (assets.length === 0) {
    return {
      ...onboardingData,
      profilePhotoUrl: onboardingData.profilePhotoUrl || onboardingData.photoUri,
    };
  }

  if (!idToken) {
    throw new Error('Firebase ID token is required to upload onboarding files');
  }

  const uploadedAssets = await uploadOnboardingAssetsViaBackend(uid, assets, idToken);
  const nextData = {
    ...onboardingData,
    vehiclePhotoUris: [...vehiclePhotoUris],
  };

  uploadedAssets.forEach((asset) => {
    if (!asset.url) return;
    if (asset.type === 'vehiclePhotoUris' && typeof asset.index === 'number') {
      nextData.vehiclePhotoUris[asset.index] = asset.url;
      return;
    }
    if (asset.type in nextData) {
      (nextData as Record<string, any>)[asset.type] = asset.url;
    }
    // Persist the backend-generated first-page preview for non-image files
    // (e.g. PDFs) as `<field>PreviewUri` so the Documents screen can render
    // a real thumbnail instead of a placeholder.
    const previewUrl = asset.previewCanonicalUrl || asset.previewUrl;
    if (previewUrl) {
      const previewField = `${asset.type.replace(/Uri$/, '')}PreviewUri`;
      (nextData as Record<string, any>)[previewField] = previewUrl;
    }
  });

  return {
    ...nextData,
    profilePhotoUrl: nextData.profilePhotoUrl || nextData.photoUri,
  };
};

// ============================================================================
// Public API
// ============================================================================

export const updateDriverProfilePhoto = async (
  uid: string,
  localImageUri: string,
  idToken?: string | null
): Promise<string> => {
  if (!uid) throw new Error('Firebase UID is required');
  if (!localImageUri) throw new Error('Missing image');
  if (isRemoteUrl(localImageUri)) return localImageUri;
  if (!idToken) throw new Error('Firebase ID token is required to update profile photo');

  const imageData = await resolveUploadDataUrl(localImageUri, 1024, 0.82);
  if (!imageData) {
    throw new Error('Failed to convert selected image to a data URL');
  }

  // The backend uploads to S3 and updates the driver's profilePhotoUrl in MongoDB.
  return uploadProfilePhotoViaBackend(uid, imageData, idToken);
};

export const submitDriverReport = async (
  uid: string,
  reportInput: DriverReportData,
  idToken?: string | null
): Promise<{ success: boolean; reportId?: string; error?: string }> => {
  try {
    if (!uid) throw new Error('Firebase UID is required');
    if (!idToken) throw new Error('Firebase ID token is required to submit a report');

    const reportId = await submitDriverReportViaBackend(uid, reportInput, idToken);
    return { success: true, reportId };
  } catch (error: any) {
    console.error('❌ Error submitting report:', error);
    return { success: false, error: error.message || 'Failed to submit report' };
  }
};

/**
 * Store complete onboarding data to MongoDB via the backend.
 */
export const storeOnboardingData = async (
  uid: string,
  phoneNumber: string,
  onboardingData: Omit<OnboardingData, 'createdAt' | 'updatedAt' | 'submittedAt'>,
  idToken?: string
): Promise<{ success: boolean; driverId?: string; error?: string }> => {
  try {
    if (!uid) throw new Error('Firebase UID is required');

    // SAFEGUARD: never clobber an existing terminal verification decision.
    try {
      const existing = await getDriverProfile(uid, idToken);
      const existingStatus = resolveDriverVerificationStatus(existing);
      if (existingStatus === 'verified' || existingStatus === 'suspended') {
        console.warn(
          `Driver ${uid} is already ${existingStatus}; skipping onboarding overwrite to preserve verification state.`
        );
        return { success: true, driverId: uid };
      }
    } catch (preCheckError) {
      console.warn('Could not pre-check existing verification status:', preCheckError);
    }

    if (!idToken) {
      throw new Error('Firebase ID token is required to store onboarding data');
    }

    const uploadedOnboardingData = await uploadOnboardingAssets(uid, onboardingData, idToken);

    // Safety net: never write an oversized Base64 blob into a document. If an image
    // could not be uploaded to storage, fail with a clear message instead of a 413.
    for (const key of Object.keys(uploadedOnboardingData)) {
      const field = (uploadedOnboardingData as Record<string, any>)[key];
      if (typeof field === 'string' && field.startsWith('data:') && field.length > 512 * 1024) {
        console.error(`Field "${key}" is still a large Base64 string — refusing oversized write.`);
        return {
          success: false,
          error: `The "${key}" image could not be uploaded. Please use a smaller image and try again.`,
        };
      }
    }

    const now = new Date().toISOString();

    // A submission (first-time or a re-upload after a rejection) always puts the
    // driver back into "under review". The backend merge-writes ($set) the
    // payload, so every verification-related field must be explicitly reset
    // here — otherwise stale admin-written fields (documentVerificationStatus,
    // status, rejectionMessage, ...) survive the update and the driver stays
    // stuck in "rejected" even though fresh documents were uploaded.
    const dataToStore: OnboardingData = {
      ...uploadedOnboardingData,
      phoneNumber,
      activeStatus: false,

      // Reset the verification decision back to "pending"
      verificationStatus: 'pending',
      documentVerificationStatus: 'pending',
      status: 'pending',
      verified: false,
      verifiedDate: null as unknown as string,
      verifiedAt: null as unknown as string,

      // Clear the previous admin rejection details
      rejectionMessage: null as unknown as string,
      rejectionReason: null as unknown as string,
      rejectedDocuments: null as unknown as string[],
      verificationNotes: null as unknown as string,

      createdAt: now,
      updatedAt: now,
      submittedAt: now,
    };

    console.log(`📝 Storing onboarding data to MongoDB via backend for UID: ${uid}`);
    await storeDriverViaBackend(uid, dataToStore, idToken);
    console.log('✅ Onboarding data stored successfully');

    return { success: true, driverId: uid };
  } catch (error: any) {
    console.error('❌ Error storing onboarding data:', error);
    return {
      success: false,
      error: error.message || 'Failed to store data',
    };
  }
};

/**
 * Fetch verification status for a driver (by UID or phone number).
 */
export const getVerificationStatus = async (uidOrPhone: string, idToken?: string) => {
  try {
    const profile = await getDriverProfile(uidOrPhone, idToken);

    if (!profile) {
      console.warn(`No verification status found for: ${uidOrPhone}`);
      return null;
    }

    const status = resolveDriverVerificationStatus(profile);
    if (!status) {
      console.warn(`Unknown verification status for ${uidOrPhone}:`, {
        verificationStatus: profile.verificationStatus,
        documentVerificationStatus: profile.documentVerificationStatus,
        status: profile.status,
        verified: profile.verified,
      });
      return null;
    }

    return {
      status,
      rejectionMessage: profile.rejectionMessage,
      rejectionReason: profile.rejectionReason,
      rejectedDocuments: profile.rejectedDocuments,
      verificationNotes: profile.verificationNotes,
    };
  } catch (error) {
    console.error('Error fetching verification status:', error);
    return null;
  }
};

/**
 * Fetch a complete driver profile (by UID or phone number) from MongoDB.
 */
/**
 * Ask the backend to generate (or reuse) a first-page PNG preview for an
 * already-stored driver document (e.g. a PDF uploaded before previews existed).
 * Returns the canonical preview URL, or '' when no preview could be generated.
 */
export const generateDriverDocumentPreview = async (
  uid: string,
  field: 'drivingLicenseUri' | 'identityProofUri' | 'rcBookUri' | 'insuranceUri',
  idToken?: string | null
): Promise<string> => {
  if (!uid) return '';
  try {
    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    if (idToken) headers['Authorization'] = `Bearer ${idToken}`;
    const response = await fetchWithTimeout(`${getApiBaseUrl()}/api/uploads/driver-doc-preview`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ uid, field }),
    });
    const body = await response.json().catch(() => null);
    if (response.ok && body?.success) {
      return String(body.previewUri || '');
    }
  } catch (error) {
    console.error('Error generating driver document preview:', error);
  }
  return '';
};

export const getDriverProfile = async (
  uidOrPhone: string,
  idToken?: string | null,
  throwOnError = false
): Promise<OnboardingData | null> => {
  try {
    const apiBase = getApiBaseUrl();
    const headers: Record<string, string> = {};
    if (idToken) headers['Authorization'] = `Bearer ${idToken}`;

    const url = isPhoneIdentifier(uidOrPhone)
      ? `${apiBase}/api/drivers/by-phone/${encodeURIComponent(uidOrPhone)}`
      : `${apiBase}/api/firestore/drivers/${encodeURIComponent(uidOrPhone)}`;

    const response = await fetchWithTimeout(url, { headers, cache: 'no-cache' });
    if (response.ok) {
      const body = await response.json().catch(() => null);
      if (body?.success && body.data) {
        return body.data as OnboardingData;
      }
    }
    if (throwOnError && response.status !== 404) {
      throw new Error('Unable to load driver profile');
    }
    return null;
  } catch (error) {
    console.error('Error fetching driver profile:', error);
    if (throwOnError) throw error;
    return null;
  }
};

export const updateDriverAvailability = async (
  uid: string,
  status: DriverAvailabilityStatus,
  idToken?: string | null
): Promise<{ success: boolean; error?: string }> => {
  try {
    if (!uid) throw new Error('Firebase UID is required');
    if (!idToken) throw new Error('Firebase ID token is required to update availability');

    const activeStatus = status === 'online';
    const changedAt = new Date().toISOString();

    await createDriverAvailabilityLogViaBackend(uid, status, changedAt, idToken);
    await setDriverAvailabilityStateViaBackend(uid, status, changedAt, idToken);
    await updateDriverViaBackend(uid, { activeStatus, updatedAt: new Date().toISOString() }, idToken);

    return { success: true };
  } catch (error: any) {
    console.error('Error updating driver availability:', error);
    return {
      success: false,
      error: error.message || 'Failed to update driver availability',
    };
  }
};

export const getLatestDriverAvailability = async (
  uid: string,
  idToken?: string | null
): Promise<DriverAvailabilityState | null> => {
  try {
    if (!uid) return null;

    const state = idToken
      ? await getDriverAvailabilityStateViaBackend(uid, idToken)
      : null;

    if (state?.status === 'online' || state?.status === 'offline') return state;

    // Fallback: derive from the driver's activeStatus in MongoDB.
    const profile = await getDriverProfile(uid, idToken);
    if (profile && typeof profile.activeStatus === 'boolean') {
      return {
        status: profile.activeStatus ? 'online' : 'offline',
        changedAt: profile.updatedAt || null,
      };
    }

    return null;
  } catch (error) {
    console.error('Error fetching latest driver availability:', error);
    return null;
  }
};
